openapi: 3.0.1
info:
  title: Employee API
  description: API for managing employee records.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /employees/admin/all:
    get:
      tags:
        - Employee
      summary: Get all employees
      operationId: getAllEmployees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
      security:
        - bearerAuth: []

  /employees/admin/find/{id}:
    get:
      tags:
        - Employee
      summary: Get employee by ID
      operationId: getEmployeeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Employee object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
      security:
        - bearerAuth: []

  /employees/admin/find:
    get:
      tags:
        - Employee
      summary: Get employees by service years less than the specified value
      operationId: getEmployeesByServiceYearsLessThan
      parameters:
        - name: serviceYears
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
      security:
        - bearerAuth: []

  /employees/admin/add:
    post:
      tags:
        - Employee
      summary: Add a new employee
      operationId: addEmployee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeAddRequest'
      responses:
        '200':
          description: Newly created employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeAddResponse'
      security:
        - bearerAuth: []

components:
  schemas:
    Employee:
      type: object
      required:
        - firstName
        - lastName
        - email
        - dateOfBirth
        - salary
        - serviceYears
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        dateOfBirth:
          type: string
          format: date
        salary:
          type: number
          format: double
        serviceYears:
          type: integer
          format: int32
        address:
          type: string
    EmployeeAddRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - dateOfBirth
        - salary
        - serviceYears
        - address
        - sinNumber
        - driverLicenceNumber
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        dateOfBirth:
          type: string
          format: date
        salary:
          type: number
          format: float
        serviceYears:
          type: integer
          format: int32
        address:
          type: string
        sinNumber:
          type: string
        driverLicenceNumber:
          type: string
    EmployeeAddResponse:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        employee:
          $ref: '#/components/schemas/Employee'